paths:
  base: '/home/snow/NEU/cricket_news/'
  data: 'dataset/66211/'
  match_id: '66211'
  commentary: '_commentary.csv'
  scorecard: '_scorecard.csv'
  highlights: '_highlights.csv'
  chunks: 'chunks/'
  extract: 'extracted/'
  revise: 'revised/'
  final_dir: 'article/'

models:
  extract: 'dolphin-phi'
  revise: 'dolphin-phi'
  generate: 'llama3'

save_options:
  save_chunks: True
  save_extract: True
  save_revise: True
  save_generate: True
  save_refine: True